In [31]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice1=a[2:6]
print(slice1)

[3 4 5 6]


In [29]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice2=a[::2]
print(slice2)

[1 3 5 7 9]


In [27]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice3=a[::3]
print(slice3)

[1 4 7]


In [33]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
slice4=a[::4]
print(slice4)

[1 5 9]


In [35]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
rev_array=a[::-1]
print(rev_array)

[9 8 7 6 5 4 3 2 1]


In [41]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=a[0:2,1:3]
print(subarr)

[[2 3]
 [5 6]]


In [43]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=a[:1,:3]
print(subarr)

[[1 2 3]]


In [45]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
col1=a[:,0]
print(col1)
row1=a[0,:]
print(row1)

[1 4 7]
[1 2 3]
