In [1]:
import numpy as np
a=np.array([10,20,30,40])
print("One Dimensional array:\n",a)

One Dimensional array:
 [10 20 30 40]


In [3]:
import numpy as np
b=np.array([[10,20,30,40],[50,60,70,80]])
print("Two Dimensional array:\n",b)

Two Dimensional array:
 [[10 20 30 40]
 [50 60 70 80]]


In [5]:
import numpy as np
c=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("Three Dimensional array:\n",c)

Three Dimensional array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [7]:
import numpy as np
d=np.zeros((3,5))
print("Array with all zeros:\n",d)

Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
import numpy as np
e=np.random.random((2,3))
print("\nRandom value:\n",e)


Random value:
 [[0.14710975 0.80578783 0.87077402]
 [0.12570881 0.97959878 0.80761609]]


In [11]:
import numpy as np
f=np.arange(20,60,5)
print("\nSequence array:\n",f)


Sequence array:
 [20 25 30 35 40 45 50 55]


In [13]:
import numpy as np
g=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
h=g.reshape(4,3)
print("\nnormal three dimensional array:\n",g,"\nreshaped array:\n",h)


normal three dimensional array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]] 
reshaped array:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [15]:
import numpy as np
g=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
i=g.flatten()
print("\nnormal three dimensional array:\n",g,"\nFlatten array:\n",i)


normal three dimensional array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]] 
Flatten array:
 [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [17]:
import numpy as np
g=np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])
print("\nArray dimension:\n",g.ndim)


Array dimension:
 3


In [19]:
import numpy as np
c=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("Shape of the array:\n",c.shape)

Shape of the array:
 (3, 4)


In [21]:
import numpy as np
c=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("Datatype of the array:\n",c.dtype)

Datatype of the array:
 int32


In [23]:
import numpy as np
c=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
size=len(c)
print("size of the array:\n",size)

size of the array:
 3


In [25]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(a)
print(newtype)
print(newtype.dtype)

[1 2 3]
[1. 2. 3.]
float64
